Add favotite products task 11
odevpl/wdp-2401 pull request #12
Opened 2024-01-19 12:22 UTC by Nataniel131

2024-01-20 23:13 UTC, Jnlietta requested changes
Chyba pomieszały Ci się branche :D w tym zadaniu masz jakby rozwiązanie dla bug-8 (Setting color variables), ale bez poprawki w settings o której pod tamtym branchem pisaliśmy, a na  branchu Setting color variables masz rozwiązania dla dwóch zadań bug-8 i task-11

2024-01-20 23:45 UTC, Nataniel131 commented
Możliwe, poprawiałem oba te zadania jeden pod drugim, więc w jakiś sposób bliżej mi nieznany mogly się pomieszać, ale jeden jak i drugi branch jest chyba prawidłowy i wszystko w nich powinno działać

2024-01-21 12:58 UTC, Jnlietta commented
Narazie Tylko zerknęłam, bo wg instruktażu powinnam dokładniej sprawić po naprawieniu konfliktów.
A co do pomieszanych branchy to utrudnia to sprawdzanie zadań, bo na branchu do zadania 8 zmiany zostały zawarte w 20 plikach (zmiany dla dwóch bugów), w dodatku teraz mam tylko dwa pull requesty do sprawdzenia, więc jakoś sobie poradziłam, żeby się zorientować który kod jest do którego zadania, ale jakby było ich pięć to szukanie tego które zadanie na którym branchu ma swój kod zabiera po prostu sporo czasu i energii. Nie mam pretensji, ale plis sprawdzaj co wysyłasz do sprawdzenia :)

2024-01-23 11:56 UTC, Nataniel131 commented
Ten branch różni się od mastera tylko dwoma plikami, gdzie dodałem wcięcia lub usunąłem puste linie kodu.

2024-01-26 16:42 UTC, merged