Task 14
odevpl/wdp-2401 pull request #13
Opened 2024-01-21 10:14 UTC by Nataniel131

2024-01-21 14:45 UTC, Jnlietta commented
Sprawdzę jak nie będzie konfliktów

2024-01-24 17:06 UTC, Jnlietta requested changes
![image](https://github.com/odevpl/wdp-2401/assets/143349472/3e484661-692f-457d-9c42-c37f6c09f82c)
hej zobacz na to zdjęcie, to jest responsywność dla tabletów, menu wg zadania powinno być normalnie rozpisane tak jak było, jedyna zmiana to była taka, że wyszukiwarki są wyżej, a menu niżej, ale nie w postaci dropdown

co do samego dropdowna, pokazuje się po kliknięciu które powoduje przesunięcie strony, wg mnie nie dobrze to wygląda więc może niech pokazuje się na hover?

2024-01-24 17:10 UTC, Jnlietta requested changes
![image](https://github.com/odevpl/wdp-2401/assets/143349472/6451a48b-9bbc-46f1-9e47-8752f30acc5c)

![image](https://github.com/odevpl/wdp-2401/assets/143349472/cbdcdfd7-2c25-4e08-874f-a44ae8b0cb8f)


co do responsywności na mniejszych urządzeniach, to tak na prawdę poza tym, że miał być dropdown w tym przypadku (tylko nie pod wyszukiwarkami, a obok nich) to nic tam nie jest dopasowane , cały MenuBar się rozjeżdża i wystaje poza viewport, pozmieniać musisz rozmiary elementów tak, aby były czytelne i mieściły się na mniejszej szerokości ekranu

2024-01-26 12:38 UTC, Jnlietta commented
Czy możesz wysłać mi screeny jak u Ciebie wygląda aplikacja po wprowadzonych zmianach w kodzie? U mnie wizualnie w działaniu aplikacji nic się nie zmieniło od ostatnich uwag, responsywność dla małych urządzeń nie działa, a dla tabletów nie została wprowadzona zmiana o jakiej mówiłam, dla laptopa dodatkowo widzę, że działa to co miało działać dla tabletu 
![image](https://github.com/odevpl/wdp-2401/assets/143349472/f1c066a2-561f-40ee-a566-2f3e89018e3b)
![image](https://github.com/odevpl/wdp-2401/assets/143349472/47223959-8f52-47fb-b6aa-d7c5feba5e51)
![image](https://github.com/odevpl/wdp-2401/assets/143349472/49fd4bda-5ce7-43bb-ae0f-9ffbbda20812)

2024-01-26 18:49 UTC, Nataniel131 commented
Sprawdź proszę teraz

2024-01-28 13:48 UTC, Jnlietta commented
![image](https://github.com/odevpl/wdp-2401/assets/143349472/fcf13091-b152-4931-862e-2cb00589868e)
Tutaj w tabletach dałabym tylko jakiś margin żeby nie były  te elementy do siebie przyklejone i reszta ok :)

2024-01-28 14:11 UTC, Jnlietta requested changes
tutaj komentarze do zmian : https://github.com/odevpl/wdp-2401/pull/13

2024-01-28 15:05 UTC, Nataniel131 commented
margines dodany w nowym commicie, już nie są ze sobą przyklejone

2024-01-28 20:34 UTC, Jnlietta approved these changes

2024-01-28 20:34 UTC, merged