Add RWD for Footer
odevpl/wdp-2401 pull request #17
Opened 2024-01-28 12:56 UTC by Nataniel131

2024-01-28 14:06 UTC, Jnlietta commented
![image](https://github.com/odevpl/wdp-2401/assets/143349472/be8e3520-356b-449d-bbae-bf6575d220e6)

Górna partia stopki (szare tło, linki ikony metod płatności) na tabletach się mieści, ale na mniejszych ekranach chce żeby były **po dwie sekcje na szerokość**, a jak w najmniejszych rozdzielczościach nie będą się mieścić, to nawet 1 na szerokość (**tylko w tych najmniejszych**). 

2024-01-28 14:08 UTC, Jnlietta commented
![image](https://github.com/odevpl/wdp-2401/assets/143349472/f94674ee-2da4-45bf-8f1e-4f13f74adb5b)
W tym dolnym pasku Klient chce żeby na tablecie copyright był do lewej, a socjalki do prawej. Tam jest obecnie specjalnie zostawione miejsce po lewej, w którym na razie niczego nie ma, ale Klient prosił o uwzględnienie że może być coś dodane i wtedy na tabletach to coś ma być wyśrodkowane i na całą szerokość (nad copyright i socjalkami). 

2024-01-28 14:10 UTC, Jnlietta requested changes
Dodałam komentarze tu https://github.com/odevpl/wdp-2401/pull/17

2024-01-28 17:49 UTC, Nataniel131 commented
pierwszą uwagę uwzględniłem, ale drugą? No dajmy spokój to tylko 1px. Korzystałem z boodstrapa i tak to bym zostawił.

2024-01-28 20:55 UTC, Jnlietta commented
ja tam treść zadania wkleiłam :) więc trzeba to uwzględnić

2024-01-28 21:09 UTC, Nataniel131 commented
O tą drugą gdzie przy 768px copyright jest na środku, a przy 767px jest już po lewej stronie tak jak w poleceniu.

2024-01-29 18:22 UTC, Jnlietta commented
image
W tym dolnym pasku Klient chce żeby na tablecie **copyright był do lewej** **( u ciebie jest wysrodkowane)**, a socjalki do prawej. Tam jest obecnie specjalnie zostawione miejsce po lewej, w którym na razie niczego nie ma, ale Klient prosił o uwzględnienie że może być coś dodane i wtedy na tabletach **to coś ma być wyśrodkowane i na całą szerokość (nad copyright i socjalkami)** **czyli trzeba dodać miejsce na "coś" akapit wyżej niż copyright i socjalki**.

2024-01-29 18:35 UTC, Jnlietta commented
![image](https://github.com/odevpl/wdp-2401/assets/143349472/3c64a311-06bb-49d7-b3f3-d09a06fa094d)
okej widzę już co miałeś na myśli z tym 1px, ale i tak tutaj widzę, że nie ma tego miejsca zostawionego na to "coś" o co klient prosił, to ma być zostawione nad copyright i socjalkami, więc może jakiś po prostu większy, wyraźniejszy margin od góry, chodzi mi o tą część: 
"Tam jest obecnie specjalnie zostawione miejsce po lewej, w którym na razie niczego nie ma, ale Klient prosił o uwzględnienie że może być coś dodane i wtedy na tabletach to coś ma być wyśrodkowane i na całą szerokość (nad copyright i socjalkami). "
W pierwotnej wersji też było zostawione to miejsce, ale z lewej więc i tu trzeba wyraźnie zostawić

2024-01-30 15:24 UTC, Nataniel131 commented
![Zrzut ekranu (159)](https://github.com/odevpl/wdp-2401/assets/141322004/0cdae814-4abb-43fb-b272-838ba23dfbea)
![Zrzut ekranu (161)](https://github.com/odevpl/wdp-2401/assets/141322004/5c0c2d0c-408a-4b8d-97d8-76fda8459eaf)

2024-01-30 15:26 UTC, Nataniel131 commented
Div który był po lewej na dużych ekranach teraz jest nad innymi na mniejszych, więc chyba naprawione.

2024-01-30 22:42 UTC, Jnlietta approved these changes

2024-01-30 22:43 UTC, merged