Setting color variables
odevpl/wdp-2401 pull request #7
Opened 2024-01-14 18:09 UTC by Nataniel131

2024-01-19 15:06 UTC, Nataniel131 commented
Dzięki za uwagę :D Już poprawione

2024-01-20 22:54 UTC, Jnlietta requested changes
Poprzedni fragment już super, ale po zmergowaniu branchy pojawiły się konflikty więc jeszcze trzeba się z nimi zmierzyć  :D

2024-01-21 17:05 UTC, Jnlietta requested changes

2024-01-21 17:22 UTC, Nataniel131 commented on src/redux/initialState.js
isFavorite zmienione na favorite

2024-01-21 17:23 UTC, Nataniel131 commented on src/components/common/ProductBox/ProductBox.js
jw.

2024-01-21 17:23 UTC, Nataniel131 commented on src/components/common/ProductBox/ProductBox.js
zmienione na handleClickFavorite

2024-01-21 17:23 UTC, Nataniel131 commented on src/components/features/NewFurniture/NewFurniture.js
jw.

2024-01-21 17:23 UTC, Nataniel131 commented on src/redux/productsRedux.js
jw.

2024-01-21 17:24 UTC, Nataniel131 commented on src/components/common/ProductBox/ProductBox.test.js
tak, test się wysypał i Patryk kazał go usunąć

2024-01-21 17:26 UTC, Nataniel131 commented on src/redux/productsRedux.js
> +const reducerName = 'products';
ona już tam była, więc dla bezpieczeństwa nie będę usuwać

2024-01-21 17:28 UTC, Nataniel131 commented on pizzeria-portal@0.1.0
plik zainstalowany razem z paczką, można usunąć

2024-01-21 17:28 UTC, Nataniel131 commented on react-scripts
jw.

2024-01-21 17:30 UTC, Jnlietta requested changes

2024-01-21 17:30 UTC, Jnlietta commented on src/redux/productsRedux.js
> +    case ADD_TO_FAVORITE:
tutaj co do nazwy to może też użyjmy zamiast ADD_TO_FAVORITE nazwę TOGGLE_PRODUCT_FAVORITE? bardziej oddaje co się tam dzieje bo po dodaniu do ulubionych jak klikniemy za drugim razem to nam sie z tych ulubionych usunie wiec ten guzik ma jakby dwa "zachowania"

2024-01-21 17:30 UTC, Jnlietta commented on src/redux/productsRedux.js
> +export const addToFavorite = payload => ({ payload, type: ADD_TO_FAVORITE });
i analogicznie addToFavorite możemy zamienić na toggleProductFavorite i też zmienić te nazwy w pozostałych plikach gdzie tego używamy

2024-01-21 17:41 UTC, Nataniel131 commented on src/redux/productsRedux.js
> +    case ADD_TO_FAVORITE:
zmienione

2024-01-21 17:42 UTC, Nataniel131 commented on src/redux/productsRedux.js
> +export const addToFavorite = payload => ({ payload, type: ADD_TO_FAVORITE });
również zmienione

2024-01-21 17:48 UTC, Jnlietta commented on src/redux/productsRedux.js
> +const reducerName = 'products';
o to ciekawe, bo ja jej nie mam u siebie w kodzie, ale widzę, że jest coś takiego zastosowane w cartRedux.js, ale ok dodaje to po prostu linijkę kodu

2024-01-21 18:04 UTC, Jnlietta requested changes

2024-01-21 18:04 UTC, Jnlietta commented on src/components/common/FeatureBox/FeatureBox.module.scss
> +<<<<<<< HEAD
o tutaj tych linijek nie powinno być  :D

2024-01-21 18:04 UTC, Jnlietta commented on src/components/common/FeatureBox/FeatureBox.module.scss
> +>>>>>>> 700b7f734c6aba7156e25a8b434245255cf63d88
i tu

2024-01-21 18:04 UTC, Jnlietta commented on src/components/layout/Footer/Footer.module.scss
> +<<<<<<< HEAD
to samo

2024-01-21 18:04 UTC, Jnlietta commented on src/components/layout/TopBar/TopBar.module.scss
> +<<<<<<< HEAD
też

2024-01-21 18:04 UTC, Jnlietta commented on src/components/layout/TopBar/TopBar.module.scss
> +>>>>>>> 700b7f734c6aba7156e25a8b434245255cf63d88
.

2024-01-21 18:04 UTC, Jnlietta commented on src/styles/settings.scss
> +<<<<<<< HEAD
tutaj też

2024-01-21 18:04 UTC, Jnlietta commented on src/styles/settings.scss
> +=======
i tuu

2024-01-21 18:04 UTC, Jnlietta commented on src/styles/settings.scss
> +<<<<<<< HEAD
i tu

2024-01-21 18:33 UTC, Jnlietta requested changes

2024-01-21 18:33 UTC, Jnlietta commented on src/components/common/ProductBox/ProductBox.js
> -        <Button variant='outline' className={clsx(favorite && styles.active)}>
usunąłeś style  do buttonu favorite, to była część bug-5, zobacz może jakie zmiany tam wprowadziłam i nie usuwaj ich z kodu tylko połącz z obecnymi taskami

2024-01-21 19:24 UTC, Nataniel131 commented
Wszystko chyba prawidłowe

2024-01-21 19:40 UTC, Jnlietta requested changes

2024-01-21 19:40 UTC, Jnlietta commented on src/components/common/ProductBox/ProductBox.js
> -        <Button variant='outline' className={clsx(favorite && styles.active)}>
Zaakceptowałeś takie rozwiązanie przy bug-5, trzeba było wtedy dodać tą wskazówkę , teraz ten bug jest już zmergowany więc nie cofajmy się, po prostu dopisz to tak jak zostało, żeby poprzednia funkcjonalność też działała bez zarzutu i zakończmy mergowanie tych dwóch zadań

2024-01-21 19:44 UTC, Jnlietta commented on src/components/common/ProductBox/ProductBox.js
> -        <Button variant='outline' className={clsx(favorite && styles.active)}>
className={clsx(favorite && styles.active)} tylko to trzeba dopisać obok variant i onClick

poza tym w propsach w komponencie Button.js jest możliwość przekazywania klasy z komponentu rodzica, pamietam, że próbowałam różnych rozwiązań i działało to które zastosowałam, a inne których próbowałam nie działały

2024-01-21 20:01 UTC, Nataniel131 commented on src/components/common/ProductBox/ProductBox.js
> -        <Button variant='outline' className={clsx(favorite && styles.active)}>
okej no dodam, mimo to że będą teraz dwie takie funkcjonalności

2024-01-21 20:45 UTC, Nataniel131 commented
więcej chyba nie ma do poprawy

2024-01-22 05:13 UTC, Jnlietta requested changes

2024-01-22 05:13 UTC, Jnlietta commented on src/components/common/ProductBox/ProductBox.js
> -        <Button variant='outline' className={clsx(favorite && styles.active)}>
to nie to samo, w bugu-5 chodziło o to by styl buttona był zależy od wartości właściwości favorite lub compared w magazynie, a u Ciebie w zadaniu 11 chodzi o to by po kliknieciu w button w magazynie zmieniała się wartość właściwości, więc te dwa zadania się uzupełniają:)

2024-01-22 12:42 UTC, Nataniel131 commented
Masz jeszcze jakieś uwagi?

2024-01-22 18:16 UTC, Jnlietta approved these changes
Ok u mnie działa, approve ;)

2024-01-22 18:17 UTC, merged